dist: xenial
sudo: false

language: node_js
node_js:
  - "10"

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run build-prod -- --baseHref=https://azbesciak.github.io/CFS/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/cfs
  on:
    branch: master
